### ISSUE TITLE
patch会导致统计出问题

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [lilydjwg/ncdu-diff#2]
patch之后会有这种结果
![image](https://user-images.githubusercontent.com/9082286/34455308-0817ee9a-edb7-11e7-9fdb-6504b51d1a70.png)
未patch是这样的
![image](https://user-images.githubusercontent.com/9082286/34455311-144e7e5e-edb7-11e7-8919-f68e8059028f.png)
下方最后统计的总量也有问题。

**Comment by lilydjwg** [comment]
原来是被我改出来的 bug 啊……

**Comment by lilydjwg** [comment]
C 语言真是糟糕，abs、labs、llabs……还有 fabs、fabsf、fabsl……而且没有警告 (╯‵□′)╯︵┻━┻

**Comment by Alkaid-Benetnash** [comment]
int64_t不应该选llabs吗？labs的参数类型long是int32_t吧？

**Comment by lilydjwg** [comment]
咦，我这里的 long 和 long long 好像是一样大？

**Comment by Alkaid-Benetnash** [comment]
应该和32还是64以及编译器都有关，都是坑不管了。
新patch在我这里是正常的， thanks!
